logging:
  level:
    hk.alien: OFF

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: 'jdbc:h2:mem:test'
    #url: 'jdbc:h2:file:/tmp/test-h2'
    driverClassName: org.h2.Driver

market-data:
  sod-file: 'classpath:marketDataSod.csv'

portfolio:
  file: 'classpath:portfolio.csv'